#!/usr/bin/env Rscript
library(knitr)
knit('antsr.Rnw',tangle=TRUE)
knit('antsr.Rnw',tangle=FALSE)
for ( i in c(1) ) {
  system('pdflatex antsr ')
  system('bibtex antsr ')
}
system('pdflatex antsr ')
system('rm *log *aux *blg ')
system('mv antsr.pdf antsr_x.pdf')
# system('scp antsr.pdf stnava,advants@frs.sourceforge.net:/home/pfs/project/a/ad/advants/ANTS/ANTS_Latest')
# system(" git checkout gh-pages ; cp antsr_x.pdf antsr.pdf ; git add antsr.pdf ; git commit -m 'ENH: update to pdf' ; git push origin gh-pages ; git checkout master ")
